### ISSUE TITLE
awusb compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by AustinXDLiu** [linux-sunxi/sunxi-livesuite#14]
awusb module compiling failed on Ubuntu20.04, any help?

~/tools/sunxi-livesuite/awusb ❯ sudo make 
make -C /lib/modules/5.7.0-050700rc4-generic/build SUBDIRS=/home/austin/tools/sunxi-livesuite/awusb modules
make[1]: Entering directory '/usr/src/linux-headers-5.7.0-050700rc4-generic'
make[2]: *** No rule to make target 'arch/x86/tools/relocs_32.c', needed by 'arch/x86/tools/relocs_32.o'.  Stop.
make[1]: *** [arch/x86/Makefile:211: archscripts] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.7.0-050700rc4-generic'
make: *** [Makefile:6: default] Error 2

**Comment by elros34** [comment]
Changing SUBDIRS=$(PWD) to M=$(PWD) in Makefile fixed the issue for me on ubuntu 20.04.
Explanation: https://stackoverflow.com/a/61285195

**Comment by AustinXDLiu** [comment]
> Changing SUBDIRS=$(PWD) to M=$(PWD) in Makefile fixed the issue for me on ubuntu 20.04.
> Explanation: https://stackoverflow.com/a/61285195

This solution works, thank you!
